apiVersion: v1
kind: Pod
metadata:
  name: config-map-pod
  labels:
    name: config
spec:
  containers:
    - name: c01
      image: centos
      args:
        - bin/bash
        - -c
        - while true; do echo ashish tripathy;sleep 5;done
      volumeMounts:
        - name: testconfigmap
          mountPath: "/tmp/config"
  volumes:
    - name: testconfigmap
      configMap:
        name: mymap
        items:
          - key: sample.conf
            path: sample.conf
