apiVersion: v1
kind: Pod
metadata:
  labels:
    test: livness
  name: liveness-test-pod
spec:
  containers:
    - name: c01
      image: ubuntu
      args:
        - bin/bash
        - -c
        - touch /temp/healthy;sleep 1500
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
