apiVersion: v1
kind: Pod
metadata: 
  name: myvolconfig
spec: 
  containers: 
    - name: c1
      image: centos
      command: ["bin/bash","-c","while true; do echo Ashish;sleep 1500;done"]
      volumeMounts: 