kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - name: c00
      image: ubuntu
      command:
        ["bin/bash", "-c", "while true;do echo hello-ashish;sleep 5;done"]
      ports:
        - containerPort: 8081
    - name: c02
      image: httpd
      ports:
        - containerPort: 80
