apiVersion: v1
kind: Pod
metadata:
  name: volm-secret
spec:
  containers:
    - name: c01
      image: centos
      args:
        - bin/bash
        - -c
        - while true; do echo ashish;sleep 1500;done
      volumeMounts:
        - name: testsecret
          mountPath: "/tmp/secert/"
  volumes:
    - name: testsecret
      secret:
        secretName: mysecret
